[build]
  command = "bash netlify/build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--no-audit --no-fund --loglevel=error"

# SPA routing: send all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
